### ISSUE TITLE
TypeError: createJWKSMock is not a function

### ISSUE THREAD

**Issue by mariusailisoaie** [Levino/mock-jwks#53] opened 2021-06-30 12:30 UTC
Hello!

I'm using mock-jwks and nock to mock the auth0 authorization in a Node.js project but after switching to Jest 27 and enabling ES modules I get this error "TypeError: createJWKSMock is not a function". The tests were working fine before I enabled ES modules in Jest. Also, I'm not doing any kind of code transformation/compilation.

This is a screenshot with the error I'm getting:

![TypeError: createJWKSMock is not a function](https://user-images.githubusercontent.com/32306385/123960054-25b42800-d9af-11eb-88d0-1c10a53c0aa5.png)

Can anyone help me with this please?

Thank you and have a good day!

**Comment by Levino** [comment] 2021-06-30 12:48
I assume you are doing the import wrong. But from this little information I cannot do much for you. I would `console.log` the imported variable to see what it actually is. At the moment it looks like `createJWKSMock` is an object, not a function, maybe the function is under the key `default` in the function? This seems to be an issue with module interoperability rather than this package. If you need further help, please create a demo repo in github with a minimal example to reproduce your issue. Until then I will close as `wontfix`.

**Closed by Levino** 2021-06-30 12:48 UTC

**Comment by mariusailisoaie** [comment] 2021-06-30 14:36
Hi again @Levino ! Your comment helped me solve the problem. This is how I imported the package in the project: ```import createJWKSMock from 'mock-jwks'```. You were right, ```createJWKSMock``` is an object and I had to use the ```default``` key in order to get the function (```createJWKSMock(url)``` -> ```createJWKSMock.default(url)```). Thank you for the package. It is very useful.

All the best and have a nice day/evening!
