### ISSUE TITLE
mock-jwks does not work with jest in Github Actions

### ISSUE THREAD

**Issue by jatinmehrotra** [Levino/mock-jwks#55] opened 2021-09-06 08:25 UTC
Locally it works like a charm but when i try to run test in github actions with jest, either it is not istalled by github actions or perhaps not being used by github actions jest runner.

**Comment by Levino** [comment] 2021-09-08 08:48
Thank you for raising this issue. Did you read the material for best practices on raising an issue in the [readme](https://github.com/Levino/mock-jwks#contributing)? If not please do so.

Specifically in this case, I would say it is obvious, that I use CircleCI for CI and not github actions. So it is fair to assume that I do  not (yet) know how to use it easily. But from what you are saying, I assume that you know quite well how to use and configure github actions. So should it not be very easy for you to provide a PR with a github action configuration which reproduces your issue? If so please go ahead and create that PR then we can investigate the issue.

From the current issue description I do not know where to start to reproduce or at least I think I will spend ages of time to try and reproduce and potentially will fail because the problem with your setup is elsewhere. So for now I am closing this issue but I am would be more than willing to reopen as soon as I have a PR which reproduces your issue.

**Closed by Levino** 2021-09-08 08:48 UTC
