### ISSUE TITLE
InvalidTokenError: no applicable key found in the JSON Web Key Set using mock-jwks token

### ISSUE THREAD

**Issue by chrisnurse** [levino/mock-jwks#65] opened 2022-10-15 07:14 UTC
If I copy and paste a token issued by AUTH0, into my unit tests, I can run end to end into my API and check user roles and permissions.

When I run exactly the same process with the token from mock-jwks, I receive the following error:

```
InvalidTokenError: no applicable key found in the JSON Web Key Set
```

This seems to imply I haven't set something up quite right for mock-jwks?

Below is a typescript wrapper I created to help launch and use mock-jwks.

If anything is wrong, I am guessing the issue would be here somewhere:

```
import jwt from "jsonwebtoken";
import jwksClient from "jwks-rsa";
import createJWKSMock from "mock-jwks";

/**
 * Convenience wrapper for mock authentication
 * @date 15/10/2022 - 08:20:34
 *
 * @export
 * @class AuthMock
 * @typedef {AuthMock}
 */
export default class AuthMock {

    /**
     * mock auth client
     * @date 15/10/2022 - 08:20:34
     *
     * @private
     * @type {*}
     */
    private static client: any;
    /**
     * jwks mock interface
     * @date 15/10/2022 - 08:20:34
     *
     * @private
     * @type {*}
     */
    private jwksMock: any;

    /**
     * Creates an instance of AuthMock.
     * @date 15/10/2022 - 08:20:34
     *
     * @constructor
     * @param {boolean} [autoStart=true]
     */
    constructor(domain: string, autoStart: boolean = true) {
        AuthMock.client = jwksClient({
            jwksUri: `https://${process.env.domain}/.well-known/jwks.json`,
        });

        this.jwksMock = createJWKSMock(domain + "/");

        if (autoStart) {
            this.Start();
        }
    }

    /**
     * get the signing key
     * @date 15/10/2022 - 08:20:34
     *
     * @private
     * @param {*} header
     * @param {*} callback
     */
    private getKey(header: any, callback: any) {
        AuthMock.client.getSigningKey(header.kid, function (err, key) {
            if (err) {
                callback(err);
                return;
            }

            const signingKey = key.getPublicKey();
            callback(null, signingKey);
        });
    }

    /**
     * get a token
     * @date 15/10/2022 - 08:20:34
     *
     * @public
     * @returns {*}
     */
    public GetToken(claims: Record<string,unknown>): any {
        return this.jwksMock.token(claims)
    }

    /**
     * get an expired token
     * @date 15/10/2022 - 08:20:34
     *
     * @public
     * @returns {*}
     */
    public getExpiredToken(): any {
        return this.jwksMock.token({
            exp: 0,
        });
    }

    /**
     * verify token
     * @date 15/10/2022 - 08:20:34
     *
     * @async
     * @param {*} token
     * @returns {unknown}
     */
    public async VerifyToken(token: any): Promise<any> {

        const verifyAuth0Token = async token => {
            return new Promise((resolve, reject) => {
                jwt.verify(token, this.getKey, { algorithms: ["RS256"] }, (err, decoded) => {
                    if (err) {
                        reject(err);
                        return;
                    }

                    resolve(decoded);
                });
            });
        };

        const decoded = await verifyAuth0Token(token);
        return decoded;
    }

    /**
     * Create headers with authorisation token
     * @date 15/10/2022 - 10:07:29
     *
     * @public
     * @param {string} token
     * @returns {*}
     */
    public GetHeaders(token: string): any {
        return {
            headers: {
                Authorization: `Bearer ${token}`
            }
        }
    }

    /**
     * Description placeholder
     * @date 15/10/2022 - 08:20:34
     *
     * @public
     */
    public Start(): void {
        this.jwksMock.start();
    }

    /**
     * Description placeholder
     * @date 15/10/2022 - 08:20:34
     *
     * @public
     */
    public Stop(): void {
        this.jwksMock.stop();
    }
}

```

**Comment by levino** [comment] 2022-10-15 07:49
Dear @chrisnurse, I do not understand the problem. Could you create a minimal reproduction repository and link it here?

Out of curiosity: Why do you wrap everything in a class? That makes it way more complicated imo. You might want to check out Eric Elliots ["composing software"](https://medium.com/javascript-scene/composing-software-the-book-f31c77fc3ddc) on the matter.

**Comment by levino** [comment] 2022-10-16 11:26
Closing this until further information is provided.

**Closed by levino** 2022-10-16 11:26 UTC

**Comment by chrisnurse** [comment] 2022-10-16 14:10
I prefer to wrap in my own class because then I can make this module appear through an API of my choosing. I've been coding for 40 years, so it's not complex, IMHO. Maybe just personal style.

All I am describing is the simple process of getting a token, then calling an API...written using express and using this module from AUTH0: express-oauth2-jwt-bearer

When I call the API using the token issued from mock-jwks, I get an error logged into the console from  express-oauth2-jwt-bearer, as described earlier.

I just have no idea where to start looking for the cause. 

Thanks for your input and efforts though.

**Comment by levino** [comment] 2022-10-16 16:38
As I said, I need a minimal repo to reproduce your error. Without code which I can execute on my machine, I would be poking around in the dark. Thank you for your understanding.

**Comment by levino** [comment] 2022-10-16 16:58
And on the matter with the class wrapper: You see I deliberately use a factory function to hold the state and not a class.
https://github.com/levino/mock-jwks/blob/f1d23ca7d30d193d55d022bb6c0c243d4126a2ce/src/index.ts#L10-L43
There is imo no benefit to use a class in this case, it provides no additional value over the factory. So I was surprised that you would wrap this factory in a class. I wanted to understand the additional value that wrapper provides because I cannot see it. I thought maybe you would be able to show me some interesting scenarios where the class is better, that is why I asked. I only linked Eric Elliots blog post series because that would spare me repeating the argumentation against classes, which of course everybody can make their own conclusions about. For me these blog posts were a break through read and have improved my code and coding skills immensely.

**Comment by chrisnurse** [comment] 2022-10-17 01:03
Understood. The position I try to hold is isolating my code from other APIs so I then code against an "internally owned" interface. That way if the underlying ("wrapped") system changes or is replaced, I hope to reduce the impact.

Sometimes....It's kind of like defining an interface when currently you only have one class that implements the interface. Do you follow YAGNI (You're not gonna need it), or, heck it's best practice because you know you'll need more implementations later, of the same interface :)

 Also, as human coders, we sometimes think like engineers and other times like artists. But in either mode, we are just seeking to express ourselves. That's why I've loved this profession all my life. Freedom to explore and learn, as you clearly do too.

**Comment by chrisnurse** [comment] 2022-10-17 01:05
I may get more time in the next week to write a complete test scenario that includes the AUTH0 library, as that is the ecosystem I work in and where I seem to be getting issues. As I mentioned...I'm not raising an issue specific to mock-jwks per se. It's just that I observe the stringified payload when I try to decode the token with AUTH0. 

I'll get back later with a more pure implementation of mock-jwks with auth0 oauth2 module.

**Comment by levino** [comment] 2025-08-09 07:15
Please open a new issue. It will take me a couple of days to have a look. It would be best if you could also link a repo with a minimal reproduction.
